name: routingpy-examples
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - shapely
  - contextily
  - python
  - jupyter
  - pyproj
  - geopandas
  - descartes
  - pip:
    - routingpy
